In [1]:
'''
Understanding Statistics in Python
'''

# Python code to demonstrate the working of mean()
# importing ststistics to handle statistical operations

import statistics

# initializing list
li = [1, 2, 3, 3, 2, 2, 2, 1]

# Using mean() to calculate the mean of the list
print("THe average of the list ' li ' is : ")
print(statistics.mean(li))

THe average of the list ' li ' is : 
2


In [4]:
# Python code 

# importing the statistics module
from statistics import median

#importing fraction module as fr
from fraction import Fraction as fr

data1 = (2,3,4,5,7,9,11)

data2 = (2.4, 5.1, 6.7, 8.9)

data3 = (fr(1,2), fr(44,12), fr(10,3), fr(2,3))
data3

data4 = (-5,-1,-12,-19,-3)

data5 = (-1,-2,-3,-4,4,3,2,1)

data6 = ('')

print("Median of data set 1 is %s" %(median((data1))))
print("Median of data set 2 is %s" %(median((data2))))
print("Median of data set 3 is %s" %(median((data3))))
print("Median of data set 4 is %s" %(median((data4))))
print("Median of data set 5 is %s" %(median((data5)))) 

Median of data set 1 is 5
Median of data set 2 is 5.9
Median of data set 3 is 2/1
Median of data set 4 is -5
Median of data set 5 is 0.0


In [5]:
# Python working with median_low() and median_high()
import statistics

set1 = [1,3,3,4,5,7]

print("Median of the set is %s" %(statistics.median(set1)))
print("High Median of the set is %s" %(statistics.median_high(set1)))
print("Low Median of the set is %s" %(statistics.median_low(set1)))


Median of the set is 3.5
High Median of the set is 4
Low Median of the set is 3


In [6]:
arr = [1,2,3,4,5]
# Finding Max 
Maximum = max(arr)
#Finding min
Minimum = min(arr)
Range  = Maximum - Minimum

In [7]:
import numpy as np 
# example 1: calculating varinace of an array
a = np.array([[1,2],[3,4]])
a
print("Variance of an array is : ", np.var(a))

Variance of an array is :  1.25


In [8]:
#Creating an arraya using stack axis = 0 means row wise array axis = 1 means column wise array
x = np.array([10,15,7,2,16])
y = ([13,0,7,4,11])
z = np.stack((x,y),axis = 0)
i = np.stack((x,y),axis = 1)
print("Variance of x : ", x.var())
print("Variance of y : ", np.var(y))
print("Variance of z : ", z.var())
print("Variance of i : ", i.var())

Variance of x :  26.8
Variance of y :  22.0
Variance of z :  26.65
Variance of i :  26.65


In [9]:
"""
numpy.stack(array, axis = 0)
join a sequence of array along a new axis.

The axis parameter specifies the index of the new axis in the dimensionbs.
if axis = 0 it will be row and if axis = 1 it will be column
"""
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.stack((a,b),axis = 0))
print(np.stack((a,b),axis = 1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [10]:
# Variance 
from statistics import variance
data1 = (2,3,4,3,2,5,6,7,8)
print("Variance of data 1 %s" %(variance(data1)))

Variance of data 1 4.777777777777778


In [13]:
# Co variance
import numpy as np
# example 1
x = [2.1,2.5,4.0,3.6]
y = [8,12,14,10]
z = np.stack((x,y),axis = 0)
b = np.stack((x),axis = 0)
print("Variance : ", np.var(b))
print("Co-Variance : ",np.cov(z))

Variance :  0.6025
Co-Variance :  [[0.80333333 1.53333333]
 [1.53333333 6.66666667]]


In [12]:
# example 2:
x = [10,15,7,2,16]
y = [13,0,7,4,11]
X = np.stack((x,y), axis = 0)
print(np.cov(X))

[[33.5   3.25]
 [ 3.25 27.5 ]]


In [14]:
# example 3:
x = np.array([[0,3,4],[1,2,4],[3,4,5]])
print("Shape of array")

Shape of array


In [15]:
# Shape Function
from numpy import array
# Example1: reshape 1D array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# shape is a tuple that gives dimensions of the array.
# shape is a tuple that gives  you an indiction of the dimension in the array.
# reshape
data = data.reshape((data.shape[0],1))
print(data.shape)

(5,)
(5, 1)


In [17]:
#example 2: Reshape 2-D to 3-D array
from numpy import array
# list of data
data = [[11,22],[33,44],[55,66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)


In [19]:
# Seed
import pandas as pd
import numpy as np
# setting a seed so the example is reproducible
np.random.seed(4272018)
df = pd.DataFrame(np.random.randint(low = 0, high = 20, size = (5,2)), columns = ['Commercials Watched', 'Product Purchases'])
print(df)
print(df['Commercials Watched'].var())
print(df[['Commercials Watched', 'Product Purchases']].cov())

   Commercials Watched  Product Purchases
0                   10                 13
1                   15                  0
2                    7                  7
3                    2                  4
4                   16                 11
33.5
                     Commercials Watched  Product Purchases
Commercials Watched                33.50               3.25
Product Purchases                   3.25              27.50


In [40]:
# Question
# Read a csv file, mean , median, mode, median_high, median_low, range, var, cov and ,manually

import pandas as pd
import statistics as st
df = pd.read_csv('Book1.csv')
print(df)
df.drop('Name', axis = 1)
# Mean
print('\n')
print('Mean Age :',st.mean(df['Age']))
print('Mean Marks : ',st.mean(df['Marks']))
# Median
print('\n')
print('Median Age : ',st.median(df['Age']))
print('Median Marks : ',st.median(df['Marks']))
# Median_High and Median_Low
print('\n')
print('Median_High Age : ',st.median_high(df['Age']))
print('Median_Low Age : ',st.median_low(df['Age']))
print('\n')
print('Median_High Marks : ',st.median_high(df['Marks']))
print('Median_Low Marks : ',st.median_low(df['Marks']))
# Mode
print('\n')
print('Mode Age : ',st.mode(df['Age']))
print('Mode Age : ',st.mode(df['Marks']))
# Variance
print('\n')
print('Variance of Age : ',df['Age'].var())
print('Variance of Marks : ',df['Marks'].var())
print('Variance of Age and Marks : ',df[['Age','Marks']].var())
# Co-Variance
print('\n')
#print('Co-Variance of Age : ',df['Age'].cov())
#print('Co-Variance of Marks : ',df['Marks'].cov())
print('Co-Variance of Age and Marks : ',df[['Age','Marks']].cov())
# Range
# Range Age
print('\n')
Maximum_Age = max(df['Age'])
Minimum_Age = min(df['Age'])
Range_Age = Maximum_Age - Minimum_Age
print('Maximum_Age : {}, Minimum_Age : {}, Range_Age : {}'.format(Maximum_Age, Minimum_Age, Range_Age))
# Range Marks
print('\n')
Maximum_Marks = max(df['Marks'])
Minimum_Marks = min(df['Marks'])
Range_Marks = Maximum_Marks - Minimum_Marks
print('Maximum_Marks : {}, Minimum_Marks : {}, Range_Marks : {}'.format(Maximum_Marks, Minimum_Marks, Range_Marks))

        Name  Age  Marks
0   Abhishek   20     79
1      Aryan   21     81
2     Shivam   20     75
3     Gourav   22     89
4      Ankit   17     80
5     Simran   18     78
6      Sahil   18     69
7      Rahul   21     79
8      Umesh   22     92
9     Sachin   18     60
10     Sumit   21     65
11    Chetan   21     80
12    Yogesh   21     77
13   Sourabh   27     69


Mean Age : 20.5
Mean Marks :  76.64285714285714


Median Age :  21.0
Median Marks :  78.5


Median_High Age :  21
Median_Low Age :  21


Median_High Marks :  79
Median_Low Marks :  78


Mode Age :  21
Mode Age :  79


Variance of Age :  6.115384615384615
Variance of Marks :  75.01648351648352
Variance of Age and Marks :  Age       6.115385
Marks    75.016484
dtype: float64


Co-Variance of Age and Marks :              Age      Marks
Age    6.115385   2.807692
Marks  2.807692  75.016484


Maximum_Age : 27, Minimum_Age : 17, Range_Age : 10


Maximum_Marks : 92, Minimum_Marks : 60, Range_Marks : 32


In [ ]:
# Read cav file data plot:
# bar plot, histogram, lineplot, scatter plot